name: unit tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
        uses: actions/checkout@v2
        - name: Run tests
        uses: cypress-io/github-action@v2
         run: |
                 npm install
                  npx jest
