name: Unit Tests
on: [push]
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
        npm install
        npm run lint
        npm run build
        npm start
        npm run test
